import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StoreProvider from './context/Context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="min-h-fit">

      <body className="min-h-fit h-full bg-black">
        <StoreProvider>
          <main className="w-full min-h-screen bg-black"> {children}</main>
          <div id="modal-root"></div>
        </StoreProvider>
      </body>

    </html>
  )
}
